name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */6 * * *' # toutes les 6h
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install github-readme-stats

      - name: Generate GitHub Stats SVG
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx github-readme-stats \
            --username AndrixNg1 \
            --token $GH_TOKEN \
            --include_private \
            --show_icons \
            --theme radical \
            --output github-stats.svg

          npx github-readme-stats \
            --username AndrixNg1 \
            --token $GH_TOKEN \
            --layout compact \
            --theme radical \
            --output top-langs.svg

      - name: Commit and push SVGs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-stats.svg top-langs.svg
          git commit -m "Update GitHub Stats and Top Languages" || echo "No changes to commit"
          git push
